In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [2]:
house = pd.read_csv('house.csv')
house

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0      221900         3       1.00         1180      5650     1.0           0   
1      538000         3       2.25         2570      7242     2.0           0   
2      180000         2       1.00          770     10000     1.0           0   
3      604000         4       3.00         1960      5000     1.0           0   
4      510000         3       2.00         1680      8080     1.0           0   
...       ...       ...        ...          ...       ...     ...         ...   
21608  360000         3       2.50         1530      1131     3.0           0   
21609  400000         4       2.50         2310      5813     2.0           0   
21610  402101         2       0.75         1020      1350     2.0           0   
21611  400000         3       2.50         1600      2388     2.0           0   
21612  325000         2       0.75         1020      1076     2.0           0   

       view  condition  grade  sqft_above  sqft_basement  yr_built  \
0         0          3      7        1180              0      1955   
1         0          3      7        2170            400      1951   
2         0          3      6         770              0      1933   
3         0          5      7        1050            910      1965   
4         0          3      8        1680              0      1987   
...     ...        ...    ...         ...            ...       ...   
21608     0          3      8        1530              0      2009   
21609     0          3      8        2310              0      2014   
21610     0          3      7        1020              0      2009   
21611     0          3      8        1600              0      2004   
21612     0          3      7        1020              0      2008   

       yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15  
0                 0    98178  47.5112 -122.257           1340        5650  
1              1991    98125  47.7210 -122.319           1690        7639  
2                 0    98028  47.7379 -122.233           2720        8062  
3                 0    98136  47.5208 -122.393           1360        5000  
4                 0    98074  47.6168 -122.045           1800        7503  
...             ...      ...      ...      ...            ...         ...  
21608             0    98103  47.6993 -122.346           1530        1509  
21609             0    98146  47.5107 -122.362           1830        7200  
21610             0    98144  47.5944 -122.299           1020        2007  
21611             0    98027  47.5345 -122.069           1410        1287  
21612             0    98144  47.5941 -122.299           1020        1357  

[21613 rows x 19 columns]

In [3]:
house.dropna(inplace=True)

In [4]:
house

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0      221900         3       1.00         1180      5650     1.0           0   
1      538000         3       2.25         2570      7242     2.0           0   
2      180000         2       1.00          770     10000     1.0           0   
3      604000         4       3.00         1960      5000     1.0           0   
4      510000         3       2.00         1680      8080     1.0           0   
...       ...       ...        ...          ...       ...     ...         ...   
21608  360000         3       2.50         1530      1131     3.0           0   
21609  400000         4       2.50         2310      5813     2.0           0   
21610  402101         2       0.75         1020      1350     2.0           0   
21611  400000         3       2.50         1600      2388     2.0           0   
21612  325000         2       0.75         1020      1076     2.0           0   

       view  condition  grade  sqft_above  sqft_basement  yr_built  \
0         0          3      7        1180              0      1955   
1         0          3      7        2170            400      1951   
2         0          3      6         770              0      1933   
3         0          5      7        1050            910      1965   
4         0          3      8        1680              0      1987   
...     ...        ...    ...         ...            ...       ...   
21608     0          3      8        1530              0      2009   
21609     0          3      8        2310              0      2014   
21610     0          3      7        1020              0      2009   
21611     0          3      8        1600              0      2004   
21612     0          3      7        1020              0      2008   

       yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15  
0                 0    98178  47.5112 -122.257           1340        5650  
1              1991    98125  47.7210 -122.319           1690        7639  
2                 0    98028  47.7379 -122.233           2720        8062  
3                 0    98136  47.5208 -122.393           1360        5000  
4                 0    98074  47.6168 -122.045           1800        7503  
...             ...      ...      ...      ...            ...         ...  
21608             0    98103  47.6993 -122.346           1530        1509  
21609             0    98146  47.5107 -122.362           1830        7200  
21610             0    98144  47.5944 -122.299           1020        2007  
21611             0    98027  47.5345 -122.069           1410        1287  
21612             0    98144  47.5941 -122.299           1020        1357  

[21613 rows x 19 columns]

In [5]:
house.drop(columns=['sqft_lot15','lat','sqft_lot','long','sqft_living15','waterfront','view'], axis=1, inplace=True)

In [6]:
house

price  bedrooms  bathrooms  sqft_living  floors  condition  grade  \
0      221900         3       1.00         1180     1.0          3      7   
1      538000         3       2.25         2570     2.0          3      7   
2      180000         2       1.00          770     1.0          3      6   
3      604000         4       3.00         1960     1.0          5      7   
4      510000         3       2.00         1680     1.0          3      8   
...       ...       ...        ...          ...     ...        ...    ...   
21608  360000         3       2.50         1530     3.0          3      8   
21609  400000         4       2.50         2310     2.0          3      8   
21610  402101         2       0.75         1020     2.0          3      7   
21611  400000         3       2.50         1600     2.0          3      8   
21612  325000         2       0.75         1020     2.0          3      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode  
0            1180              0      1955             0    98178  
1            2170            400      1951          1991    98125  
2             770              0      1933             0    98028  
3            1050            910      1965             0    98136  
4            1680              0      1987             0    98074  
...           ...            ...       ...           ...      ...  
21608        1530              0      2009             0    98103  
21609        2310              0      2014             0    98146  
21610        1020              0      2009             0    98144  
21611        1600              0      2004             0    98027  
21612        1020              0      2008             0    98144  

[21613 rows x 12 columns]

In [7]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   price          21613 non-null  int64  
 1   bedrooms       21613 non-null  int64  
 2   bathrooms      21613 non-null  float64
 3   sqft_living    21613 non-null  int64  
 4   floors         21613 non-null  float64
 5   condition      21613 non-null  int64  
 6   grade          21613 non-null  int64  
 7   sqft_above     21613 non-null  int64  
 8   sqft_basement  21613 non-null  int64  
 9   yr_built       21613 non-null  int64  
 10  yr_renovated   21613 non-null  int64  
 11  zipcode        21613 non-null  int64  
dtypes: float64(2), int64(10)
memory usage: 2.0 MB


In [8]:
house['bathrooms'] = house['bathrooms'].astype(int)

In [9]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   price          21613 non-null  int64  
 1   bedrooms       21613 non-null  int64  
 2   bathrooms      21613 non-null  int32  
 3   sqft_living    21613 non-null  int64  
 4   floors         21613 non-null  float64
 5   condition      21613 non-null  int64  
 6   grade          21613 non-null  int64  
 7   sqft_above     21613 non-null  int64  
 8   sqft_basement  21613 non-null  int64  
 9   yr_built       21613 non-null  int64  
 10  yr_renovated   21613 non-null  int64  
 11  zipcode        21613 non-null  int64  
dtypes: float64(1), int32(1), int64(10)
memory usage: 1.9 MB


In [10]:
house['floors'] = house['floors'].astype(int)

In [11]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          21613 non-null  int64
 1   bedrooms       21613 non-null  int64
 2   bathrooms      21613 non-null  int32
 3   sqft_living    21613 non-null  int64
 4   floors         21613 non-null  int32
 5   condition      21613 non-null  int64
 6   grade          21613 non-null  int64
 7   sqft_above     21613 non-null  int64
 8   sqft_basement  21613 non-null  int64
 9   yr_built       21613 non-null  int64
 10  yr_renovated   21613 non-null  int64
 11  zipcode        21613 non-null  int64
dtypes: int32(2), int64(10)
memory usage: 1.8 MB


In [12]:
house.reset_index(drop=True)

price  bedrooms  bathrooms  sqft_living  floors  condition  grade  \
0      221900         3          1         1180       1          3      7   
1      538000         3          2         2570       2          3      7   
2      180000         2          1          770       1          3      6   
3      604000         4          3         1960       1          5      7   
4      510000         3          2         1680       1          3      8   
...       ...       ...        ...          ...     ...        ...    ...   
21608  360000         3          2         1530       3          3      8   
21609  400000         4          2         2310       2          3      8   
21610  402101         2          0         1020       2          3      7   
21611  400000         3          2         1600       2          3      8   
21612  325000         2          0         1020       2          3      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode  
0            1180              0      1955             0    98178  
1            2170            400      1951          1991    98125  
2             770              0      1933             0    98028  
3            1050            910      1965             0    98136  
4            1680              0      1987             0    98074  
...           ...            ...       ...           ...      ...  
21608        1530              0      2009             0    98103  
21609        2310              0      2014             0    98146  
21610        1020              0      2009             0    98144  
21611        1600              0      2004             0    98027  
21612        1020              0      2008             0    98144  

[21613 rows x 12 columns]

In [13]:
X = house.drop(['price', 'yr_built', 'yr_renovated', 'zipcode', 'sqft_above', 'sqft_basement'], axis=1)
y = house['price']
y = y.values.reshape(-1,1)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=234)

In [15]:
from sklearn.metrics import r2_score

In [16]:
lr = LinearRegression()

In [17]:
lr.fit(X_train, y_train)

LinearRegression()

In [18]:
y_pred = lr.predict(X_test)

In [19]:
y_pred

array([[561063.04914427],
       [725598.86657731],
       [865916.32421925],
       ...,
       [836531.13353852],
       [307514.71050959],
       [132014.2491768 ]])

In [20]:
r2_score(y_test, y_pred)

0.5959985680088673

In [21]:
score = []
for i in range(1000):
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=i)
    lr = LinearRegression()
    lr.fit(X_train, y_train)
    y_pred = lr.predict(X_test)
    score.append(r2_score(y_test, y_pred))

In [22]:
np.argmax(score)

234

In [23]:
score[52]

0.5907500903165236

In [24]:
X_test

bedrooms  bathrooms  sqft_living  floors  condition  grade
10033         4          1         2000       1          3      7
20870         3          2         1890       2          3      7
21323         3          3         3530       2          3     10
12147         3          1         1660       1          3      7
15145         2          1         1290       1          3      7
...         ...        ...          ...     ...        ...    ...
19127         3          2         2430       2          3      8
4202          3          2         3240       2          3      7
16669         4          2         2040       2          3      8
19332         3          2         1670       2          4      7
2289          3          1         1780       1          3      7

[4323 rows x 6 columns]

In [25]:
lr.predict(pd.DataFrame([[4,1,2000,1,3,7]], columns=['bedrooms','bathrooms','sqft_living','floors','condition','grade']))

array([[404516.27707804]])

In [26]:
y_test

array([[ 228000],
       [ 409000],
       [1500000],
       ...,
       [ 500000],
       [ 289000],
       [ 354950]], dtype=int64)

## Polynomial Regression

In [27]:
from sklearn.preprocessing import PolynomialFeatures

In [28]:
poly  = PolynomialFeatures(degree=1)

In [29]:
X_poly = poly.fit_transform(X_train)

In [30]:
X_poly

array([[1., 4., 2., ..., 1., 4., 6.],
       [1., 3., 2., ..., 2., 3., 8.],
       [1., 2., 1., ..., 1., 4., 6.],
       ...,
       [1., 2., 1., ..., 1., 3., 8.],
       [1., 5., 1., ..., 1., 3., 7.],
       [1., 3., 3., ..., 2., 3., 8.]])

In [31]:
L1 = LinearRegression()

In [32]:
L1.fit(X_poly, y_train)

LinearRegression()

In [33]:
X_test_poly = poly.fit_transform(X_test)

In [34]:
y_pred = L1.predict(X_test_poly)

In [35]:
y_pred

array([[ 404516.27707805],
       [ 404383.00539333],
       [1086464.89563793],
       ...,
       [ 490340.96083772],
       [ 415864.43717875],
       [ 407887.69604719]])

In [36]:
r2_score(y_test, y_pred)

0.5804108109461523